set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN Y18 [get_ports clk]
create_clock -name clk_100mhz -period 10.000 [get_ports clk]
create_generated_clock -name clk_sys -source [get_ports clk] -divide_by 20 [get_pins clk_sys_bufg/O]
create_generated_clock -name vga_pixel_clk -source [get_ports clk] -divide_by 2 [get_pins vga_clk_bufg/O]

set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN P20 [get_ports reset_n]
set_property PULLDOWN true [get_ports reset_n]

# P1 matrix keypad
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_row[*]}]
set_property PACKAGE_PIN L5 [get_ports {keyboard_row[0]}]
set_property PACKAGE_PIN L4 [get_ports {keyboard_row[1]}]
set_property PACKAGE_PIN J6 [get_ports {keyboard_row[2]}]
set_property PACKAGE_PIN K6 [get_ports {keyboard_row[3]}]
set_property PULLUP true [get_ports {keyboard_row[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_col[*]}]
set_property PACKAGE_PIN M2 [get_ports {keyboard_col[0]}]
set_property PACKAGE_PIN L3 [get_ports {keyboard_col[1]}]
set_property PACKAGE_PIN K3 [get_ports {keyboard_col[2]}]
set_property PACKAGE_PIN J4 [get_ports {keyboard_col[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports btn_up]
set_property PACKAGE_PIN R1 [get_ports btn_up]
set_property IOSTANDARD LVCMOS33 [get_ports btn_down]
set_property PACKAGE_PIN P1 [get_ports btn_down]
set_property IOSTANDARD LVCMOS33 [get_ports btn_left]
set_property PACKAGE_PIN P5 [get_ports btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports btn_right]
set_property PACKAGE_PIN P4 [get_ports btn_right]
set_property IOSTANDARD LVCMOS33 [get_ports btn_center]
set_property PACKAGE_PIN P2 [get_ports btn_center]

set_property IOSTANDARD LVCMOS33 [get_ports {switch[*]}]
set_property PACKAGE_PIN Y9 [get_ports {switch[23]}]
set_property PACKAGE_PIN W9 [get_ports {switch[22]}]
set_property PACKAGE_PIN Y7 [get_ports {switch[21]}]
set_property PACKAGE_PIN Y8 [get_ports {switch[20]}]
set_property PACKAGE_PIN AB8 [get_ports {switch[19]}]
set_property PACKAGE_PIN AA8 [get_ports {switch[18]}]
set_property PACKAGE_PIN V8 [get_ports {switch[17]}]
set_property PACKAGE_PIN V9 [get_ports {switch[16]}]
set_property PACKAGE_PIN AB6 [get_ports {switch[15]}]
set_property PACKAGE_PIN AB7 [get_ports {switch[14]}]
set_property PACKAGE_PIN V7 [get_ports {switch[13]}]
set_property PACKAGE_PIN AA6 [get_ports {switch[12]}]
set_property PACKAGE_PIN Y6 [get_ports {switch[11]}]
set_property PACKAGE_PIN T6 [get_ports {switch[10]}]
set_property PACKAGE_PIN R6 [get_ports {switch[9]}]
set_property PACKAGE_PIN V5 [get_ports {switch[8]}]
set_property PACKAGE_PIN U6 [get_ports {switch[7]}]
set_property PACKAGE_PIN W5 [get_ports {switch[6]}]
set_property PACKAGE_PIN W6 [get_ports {switch[5]}]
set_property PACKAGE_PIN U5 [get_ports {switch[4]}]
set_property PACKAGE_PIN T5 [get_ports {switch[3]}]
set_property PACKAGE_PIN T4 [get_ports {switch[2]}]
set_property PACKAGE_PIN R4 [get_ports {switch[1]}]
set_property PACKAGE_PIN W4 [get_ports {switch[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {rled[*]}]
set_property PACKAGE_PIN N19 [get_ports {rled[0]}]
set_property PACKAGE_PIN N20 [get_ports {rled[1]}]
set_property PACKAGE_PIN M20 [get_ports {rled[2]}]
set_property PACKAGE_PIN K13 [get_ports {rled[3]}]
set_property PACKAGE_PIN K14 [get_ports {rled[4]}]
set_property PACKAGE_PIN M13 [get_ports {rled[5]}]
set_property PACKAGE_PIN L13 [get_ports {rled[6]}]
set_property PACKAGE_PIN K17 [get_ports {rled[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {yled[*]}]
set_property PACKAGE_PIN J17 [get_ports {yled[0]}]
set_property PACKAGE_PIN L14 [get_ports {yled[1]}]
set_property PACKAGE_PIN L15 [get_ports {yled[2]}]
set_property PACKAGE_PIN L16 [get_ports {yled[3]}]
set_property PACKAGE_PIN K16 [get_ports {yled[4]}]
set_property PACKAGE_PIN M15 [get_ports {yled[5]}]
set_property PACKAGE_PIN M18 [get_ports {yled[6]}]
set_property PACKAGE_PIN M17 [get_ports {yled[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gled[*]}]
set_property PACKAGE_PIN A21 [get_ports {gled[0]}]
set_property PACKAGE_PIN E22 [get_ports {gled[1]}]
set_property PACKAGE_PIN D22 [get_ports {gled[2]}]
set_property PACKAGE_PIN E21 [get_ports {gled[3]}]
set_property PACKAGE_PIN D21 [get_ports {gled[4]}]
set_property PACKAGE_PIN G21 [get_ports {gled[5]}]
set_property PACKAGE_PIN G22 [get_ports {gled[6]}]
set_property PACKAGE_PIN F21 [get_ports {gled[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_in]
set_property PACKAGE_PIN V18 [get_ports uart_tx_in]

set_property IOSTANDARD LVCMOS33 [get_ports buzzer_output]
set_property PACKAGE_PIN A19 [get_ports buzzer_output]

# 12-bit VGA output. Pin mapping is from Minisys hardware manual v1.1, Fig. 1-9.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[*]}]
set_property PACKAGE_PIN G17 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN G18 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J15 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN H15 [get_ports {vga_r[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[*]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H18 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN J22 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN H22 [get_ports {vga_g[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[*]}]
set_property PACKAGE_PIN H20 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN G20 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K21 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN K22 [get_ports {vga_b[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property PACKAGE_PIN M21 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]
set_property PACKAGE_PIN L21 [get_ports vga_vsync]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
