set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN Y18 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN P20 [get_ports reset_n]
set_property PULLDOWN true [get_ports reset_n]

set_property IOSTANDARD LVCMOS33 [get_ports btn_down]
set_property PACKAGE_PIN P1 [get_ports btn_down]
set_property IOSTANDARD LVCMOS33 [get_ports btn_left]
set_property PACKAGE_PIN P5 [get_ports btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports btn_right]
set_property PACKAGE_PIN P4 [get_ports btn_right]
set_property IOSTANDARD LVCMOS33 [get_ports btn_center]
set_property PACKAGE_PIN P2 [get_ports btn_center]

set_property IOSTANDARD LVCMOS33 [get_ports {switch[*]}]
set_property PACKAGE_PIN Y9 [get_ports {switch[23]}]
set_property PACKAGE_PIN W9 [get_ports {switch[22]}]
set_property PACKAGE_PIN Y7 [get_ports {switch[21]}]
set_property PACKAGE_PIN Y8 [get_ports {switch[20]}]
set_property PACKAGE_PIN AB8 [get_ports {switch[19]}]
set_property PACKAGE_PIN AA8 [get_ports {switch[18]}]
set_property PACKAGE_PIN V8 [get_ports {switch[17]}]
set_property PACKAGE_PIN V9 [get_ports {switch[16]}]
set_property PACKAGE_PIN AB6 [get_ports {switch[15]}]
set_property PACKAGE_PIN AB7 [get_ports {switch[14]}]
set_property PACKAGE_PIN V7 [get_ports {switch[13]}]
set_property PACKAGE_PIN AA6 [get_ports {switch[12]}]
set_property PACKAGE_PIN Y6 [get_ports {switch[11]}]
set_property PACKAGE_PIN T6 [get_ports {switch[10]}]
set_property PACKAGE_PIN R6 [get_ports {switch[9]}]
set_property PACKAGE_PIN V5 [get_ports {switch[8]}]
set_property PACKAGE_PIN U6 [get_ports {switch[7]}]
set_property PACKAGE_PIN W5 [get_ports {switch[6]}]
set_property PACKAGE_PIN W6 [get_ports {switch[5]}]
set_property PACKAGE_PIN U5 [get_ports {switch[4]}]
set_property PACKAGE_PIN T5 [get_ports {switch[3]}]
set_property PACKAGE_PIN T4 [get_ports {switch[2]}]
set_property PACKAGE_PIN R4 [get_ports {switch[1]}]
set_property PACKAGE_PIN W4 [get_ports {switch[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {rled[*]}]
set_property PACKAGE_PIN N19 [get_ports {rled[0]}]
set_property PACKAGE_PIN N20 [get_ports {rled[1]}]
set_property PACKAGE_PIN M20 [get_ports {rled[2]}]
set_property PACKAGE_PIN K13 [get_ports {rled[3]}]
set_property PACKAGE_PIN K14 [get_ports {rled[4]}]
set_property PACKAGE_PIN M13 [get_ports {rled[5]}]
set_property PACKAGE_PIN L13 [get_ports {rled[6]}]
set_property PACKAGE_PIN K17 [get_ports {rled[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {yled[*]}]
set_property PACKAGE_PIN J17 [get_ports {yled[0]}]
set_property PACKAGE_PIN L14 [get_ports {yled[1]}]
set_property PACKAGE_PIN L15 [get_ports {yled[2]}]
set_property PACKAGE_PIN L16 [get_ports {yled[3]}]
set_property PACKAGE_PIN K16 [get_ports {yled[4]}]
set_property PACKAGE_PIN M15 [get_ports {yled[5]}]
set_property PACKAGE_PIN M18 [get_ports {yled[6]}]
set_property PACKAGE_PIN M17 [get_ports {yled[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gled[*]}]
set_property PACKAGE_PIN A21 [get_ports {gled[0]}]
set_property PACKAGE_PIN E22 [get_ports {gled[1]}]
set_property PACKAGE_PIN D22 [get_ports {gled[2]}]
set_property PACKAGE_PIN E21 [get_ports {gled[3]}]
set_property PACKAGE_PIN D21 [get_ports {gled[4]}]
set_property PACKAGE_PIN G21 [get_ports {gled[5]}]
set_property PACKAGE_PIN G22 [get_ports {gled[6]}]
set_property PACKAGE_PIN F21 [get_ports {gled[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_in]
set_property PACKAGE_PIN V18 [get_ports uart_tx_in]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]